name: showcase_the_movie_guide
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^5.0.2
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  json_annotation: ^4.4.0
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  webview_flutter_plus: ^0.3.0+2
  flash: ^2.0.3+2
  flutter_bloc: ^8.0.1
  auto_route: ^3.2.4
  get_it: ^7.2.0
  injectable: ^1.5.3
  flutter_svg: ^1.0.3
  infinite_scroll_pagination: ^3.1.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.5
  auto_route_generator: ^3.2.3
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg